swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /documento_programa/:
    get:
      tags:
      - documento_programa
      description: get DocumentoPrograma
      operationId: DocumentoProgramaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DocumentoPrograma'
        "404":
          description: not found resource
    post:
      tags:
      - documento_programa
      description: create DocumentoPrograma
      operationId: DocumentoProgramaController.Post
      parameters:
      - in: body
        name: body
        description: body for DocumentoPrograma content
        required: true
        schema:
          $ref: '#/definitions/models.DocumentoPrograma'
      responses:
        "201":
          description: '{int} models.DocumentoPrograma'
        "400":
          description: the request contains incorrect syntax
  /documento_programa/{id}:
    get:
      tags:
      - documento_programa
      description: get DocumentoPrograma by id
      operationId: DocumentoProgramaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DocumentoPrograma'
        "404":
          description: not found resource
    put:
      tags:
      - documento_programa
      description: update the DocumentoPrograma
      operationId: DocumentoProgramaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for DocumentoPrograma content
        required: true
        schema:
          $ref: '#/definitions/models.DocumentoPrograma'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DocumentoPrograma'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - documento_programa
      description: delete the DocumentoPrograma
      operationId: DocumentoProgramaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /soporte_documento_programa/:
    get:
      tags:
      - soporte_documento_programa
      description: get SoporteDocumentoPrograma
      operationId: SoporteDocumentoProgramaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteDocumentoPrograma'
        "404":
          description: not found resource
    post:
      tags:
      - soporte_documento_programa
      description: create SoporteDocumentoPrograma
      operationId: SoporteDocumentoProgramaController.Post
      parameters:
      - in: body
        name: body
        description: body for SoporteDocumentoPrograma content
        required: true
        schema:
          $ref: '#/definitions/models.SoporteDocumentoPrograma'
      responses:
        "201":
          description: '{int} models.SoporteDocumentoPrograma'
        "400":
          description: the request contains incorrect syntax
  /soporte_documento_programa/{id}:
    get:
      tags:
      - soporte_documento_programa
      description: get SoporteDocumentoPrograma by id
      operationId: SoporteDocumentoProgramaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteDocumentoPrograma'
        "404":
          description: not found resource
    put:
      tags:
      - soporte_documento_programa
      description: update the SoporteDocumentoPrograma
      operationId: SoporteDocumentoProgramaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for SoporteDocumentoPrograma content
        required: true
        schema:
          $ref: '#/definitions/models.SoporteDocumentoPrograma'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteDocumentoPrograma'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - soporte_documento_programa
      description: delete the SoporteDocumentoPrograma
      operationId: SoporteDocumentoProgramaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /tipo_documento_programa/:
    get:
      tags:
      - tipo_documento_programa
      description: get TipoDocumentoPrograma
      operationId: TipoDocumentoProgramaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDocumentoPrograma'
        "404":
          description: not found resource
    post:
      tags:
      - tipo_documento_programa
      description: create TipoDocumentoPrograma
      operationId: TipoDocumentoProgramaController.Post
      parameters:
      - in: body
        name: body
        description: body for TipoDocumentoPrograma content
        required: true
        schema:
          $ref: '#/definitions/models.TipoDocumentoPrograma'
      responses:
        "201":
          description: '{int} models.TipoDocumentoPrograma'
        "400":
          description: the request contains incorrect syntax
  /tipo_documento_programa/{id}:
    get:
      tags:
      - tipo_documento_programa
      description: get TipoDocumentoPrograma by id
      operationId: TipoDocumentoProgramaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDocumentoPrograma'
        "404":
          description: not found resource
    put:
      tags:
      - tipo_documento_programa
      description: update the TipoDocumentoPrograma
      operationId: TipoDocumentoProgramaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TipoDocumentoPrograma content
        required: true
        schema:
          $ref: '#/definitions/models.TipoDocumentoPrograma'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDocumentoPrograma'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - tipo_documento_programa
      description: delete the TipoDocumentoPrograma
      operationId: TipoDocumentoProgramaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
definitions:
  models.DocumentoPrograma:
    title: DocumentoPrograma
    type: object
    properties:
      Activo:
        type: boolean
      FechaCreacion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      NumeroOrden:
        type: number
        format: double
      PeriodoId:
        type: integer
        format: int64
      ProgramaId:
        type: integer
        format: int64
      TipoDocumentoProgramaId:
        $ref: '#/definitions/models.TipoDocumentoPrograma'
  models.SoporteDocumentoPrograma:
    title: SoporteDocumentoPrograma
    type: object
    properties:
      DocumentoId:
        type: integer
        format: int64
      DocumentoProgramaId:
        $ref: '#/definitions/models.DocumentoPrograma'
      FechaCreacion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      PersonaId:
        type: integer
        format: int64
  models.TipoDocumentoPrograma:
    title: TipoDocumentoPrograma
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Extension:
        type: string
      FechaCreacion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
      Tamano:
        type: number
        format: double
tags:
- name: tipo_documento_programa
  description: |
    TipoDocumentoProgramaController operations for TipoDocumentoPrograma
- name: documento_programa
  description: |
    DocumentoProgramaController operations for DocumentoPrograma
- name: soporte_documento_programa
  description: |
    SoporteDocumentoProgramaController operations for SoporteDocumentoPrograma
